image: docker:git

services: 
  - docker:dind

variables:
  IMAGE_NAME: chimbosonic/unbound

before_script:
  - echo "$REGISTRY_PASSWORD" | docker login -u "$REGISTRY_USER" --password-stdin

stages:
  - Build
  - Release

Build image:
  stage: Build
  only:
    changes:
      - Dockerfile
      - config/**
      - installer.sh
  script:
    - export TIME_STAMP=$(date -u +'%Y-%m-%dT%H:%M:%SZ')
    - docker build --build-arg BUILD_DATE=$TIME_STAMP --build-arg VCS_REF=$CI_COMMIT_SHORT_SHA -t $IMAGE_NAME -t $IMAGE_NAME:$CI_COMMIT_SHORT_SHA .
    - docker image ls
    - docker push $IMAGE_NAME:$CI_COMMIT_SHORT_SHA

Release image:
  stage: Release
  only:
    refs:
      - master
    changes:
      - Dockerfile
      - config/**
      - installer.sh
  script:
    - docker pull $IMAGE_NAME:$CI_COMMIT_SHORT_SHA
    - docker tag $IMAGE_NAME:$CI_COMMIT_SHORT_SHA $IMAGE_NAME:latest
    - docker push $IMAGE_NAME:latest
